services:
  logto:
    image: svhd/logto:latest
    ports:
      - 3101:3001
      - 3102:3002
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DB_URL=postgresql://logto:logto@postgresql:5432/logto
      - ENDPOINT=https://ethical-incident-barbara-proceedings.trycloudflare.com
      - ADMIN_ENDPOINT=https://kernel-license-perry-stretch.trycloudflare.com
      - TRUST_PROXY_HEADER=true
    entrypoint: ["sh", "-c", "npm start"]

  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=logto
      - POSTGRES_PASSWORD=logto
      - POSTGRES_DB=logto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logto"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - logto

volumes:
  caddy_data:
  caddy_config:
